# Generated by Django 6.0.4 on 2026-04-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_eventuser_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventuser",
            name="admin_requires_referral_code",
        ),
        migrations.AlterField(
            model_name="eventuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="eventuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("vendor", "Vendor"),
                    ("admin", "Admin"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
