# Generated by Django 6.0.4 on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_eventuser_admin_requires_referral_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventuser",
            name="email_verified",
            field=models.BooleanField(default=True),
        ),
    ]
