# Generated by Django 6.0.4 on 2026-05-01 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0002_alter_service_service_type_event_eventservicebooking_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="client",
        ),
        migrations.RemoveConstraint(
            model_name="eventservicebooking",
            name="unique_event_service_booking",
        ),
        migrations.RemoveField(
            model_name="eventservicebooking",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventservicebooking",
            name="service",
        ),
        migrations.RemoveField(
            model_name="eventservicebooking",
            name="vendor",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="EventServiceBooking",
        ),
    ]
